"""Add cache expiry column

Revision ID: 8a389e11637b
Revises: eb5168ad3f96
Create Date: 2023-03-14 23:25:07.789647

"""
import datetime

from alembic import op
import sqlalchemy as sa

from grd.database.models import User


# revision identifiers, used by Alembic.
revision = "8a389e11637b"
down_revision = "eb5168ad3f96"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("cache_expiry", sa.Interval(), nullable=True))
    op.get_bind().execute(
        sa.update(User).values(
            cache_expiry=datetime.timedelta(days=1),
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "cache_expiry")
    # ### end Alembic commands ###
