"""empty message

Revision ID: aabcf8edaffc
Revises: 8a389e11637b
Create Date: 2023-03-19 15:43:50.376434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabcf8edaffc'
down_revision = '8a389e11637b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
