"""empty message

Revision ID: ab386fa3838e
Revises: aabcf8edaffc
Create Date: 2023-03-19 17:51:12.086234

"""
import datetime

from alembic import op
import sqlalchemy as sa

from grd.database.models import TZDateTime, User


# revision identifiers, used by Alembic.
revision = "ab386fa3838e"
down_revision = "aabcf8edaffc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "response_cache", sa.Column("modified_at", TZDateTime(), nullable=True)
    )
    op.add_column("response_cache", sa.Column("etag", sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.get_bind().execute(
        sa.update(User)
        .values(cache_expiry=None)
        .where(User.cache_expiry == datetime.timedelta(days=1))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response_cache", "etag")
    op.drop_column("response_cache", "modified_at")
    # ### end Alembic commands ###
