import datetime
from typing import Any

from sqlalchemy import DateTime, JSON, TypeDecorator
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    mapped_column,
)


# https://docs.sqlalchemy.org/en/20/core/custom_types.html#store-timezone-aware-timestamps-as-timezone-naive-utc
class TZDateTime(TypeDecorator):
    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        elif not value.tzinfo:
            # Interpret as local time
            value = value.astimezone()

        return value.astimezone(datetime.timezone.utc).replace(tzinfo=None)

    def process_result_value(self, value, dialect):
        if value is not None:
            value = value.replace(tzinfo=datetime.timezone.utc)
        return value


class Base(MappedAsDataclass, DeclarativeBase, kw_only=True):
    ...


# Define a naming convention to help alembic with autogenerated migrations
# https://alembic.sqlalchemy.org/en/latest/naming.html
Base.metadata.naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Response(Base, kw_only=True):
    """Stores a key-value mapping of cached responses."""

    __tablename__ = "response_cache"

    created_at: Mapped[datetime.datetime] = mapped_column(
        TZDateTime,
        default=datetime.datetime.now,
    )
    modified_at: Mapped[datetime.datetime | None] = mapped_column(
        TZDateTime,
        default=None,
    )
    key: Mapped[str] = mapped_column(primary_key=True)
    value: Mapped[Any] = mapped_column(JSON)
    etag: Mapped[str | None] = mapped_column(default=None)


class User(Base, kw_only=True):
    """Stores various user settings."""

    __tablename__ = "user"

    id: Mapped[int] = mapped_column(primary_key=True)

    github_token: Mapped[str | None] = mapped_column(default=None)

    cache_expiry: Mapped[datetime.timedelta | None] = mapped_column(default=None)


if __name__ == "__main__":
    from sqlalchemy import create_engine

    engine = create_engine("sqlite+pysqlite:///:memory:", echo=True)
    Base.metadata.create_all(engine)
